CREATE TABLE FROM_CONFIG(
    TRANSPORT_ID VARCHAR2(10),
    TRANSPORT_PASSWORD VARCHAR2(45),
    PARTY_ID VARCHAR2(10) NOT NULL,
    PARTY_DESCRIPTION VARCHAR2(200),
    ROUTING_ID VARCHAR2(39),
    ROUTING_DESCRIPTION VARCHAR2(200),
    SIGN_ID VARCHAR2(4),
    SUBSTITUTE_PARTY_ID VARCHAR2(10),
    CONSTRAINT FROM_CONFIG_PK1 PRIMARY KEY (PARTY_ID)
)