CREATE TABLE SCHEDULE_CONFIG(
    TASK VARCHAR2(30) NOT NULL,
    ENABLE VARCHAR2(1),
    SCHEDULE_TYPE VARCHAR2(10),
    SCHEDULE_WEEK VARCHAR2(15),
    SCHEDULE_TIME VARCHAR2(50),
    SCHEDULE_PERIOD VARCHAR2(10),
    SCHEDULE_RANGE VARCHAR2(15),
    CONSTRAINT SCHEDULE_CONFIG_PK1 PRIMARY KEY (TASK)
)