CREATE TABLE SIGN_CONFIG 
(
    SIGN_ID VARCHAR2(4) NOT NULL,
    SIGN_TYPE VARCHAR2(10) DEFAULT NULL,
    PFX_PATH VARCHAR2(100) DEFAULT NULL,
    SIGN_PASSWORD VARCHAR2(60) NOT NULL,
    CONSTRAINT SIGN_CONFIG_PK1 PRIMARY KEY (SIGN_ID)
)