CREATE TABLE TASK_CONFIG(
    CATEGORY_TYPE VARCHAR2(5) NOT NULL,
    PROCESS_TYPE VARCHAR2(10) NOT NULL,
    TASK VARCHAR2(15) NOT NULL,
    SRC_PATH VARCHAR2(200),
    TARGET_PATH VARCHAR2(200),
    FILE_FORMAT VARCHAR2(20),
    VERSION VARCHAR2(5),
    ENCODING VARCHAR2(15),
    TRANS_CHINESE_DATE VARCHAR2(1),
    CONSTRAINT TASK_CONFIG_PK1 PRIMARY KEY ( CATEGORY_TYPE, PROCESS_TYPE, TASK )
)