CREATE TABLE TO_CONFIG(
    PARTY_ID VARCHAR2(10) NOT NULL,
    PARTY_DESCRIPTION VARCHAR2(200),
    ROUTING_ID VARCHAR2(39),
    ROUTING_DESCRIPTION VARCHAR2(200),
    FROM_PARTY_ID VARCHAR2(10) NOT NULL,
    CONSTRAINT TO_CONFIG_PK1 PRIMARY KEY (FROM_PARTY_ID, PARTY_ID)
)