CREATE TABLE TURNKEY_MESSAGE_LOG_DETAIL(
    SEQNO VARCHAR2(8) NOT NULL,
    SUBSEQNO VARCHAR2(5) NOT NULL,
    PROCESS_DTS VARCHAR2(17),
    TASK VARCHAR2(30) NOT NULL,
    STATUS VARCHAR2(5),
    FILENAME VARCHAR2(300),
    UUID VARCHAR2(40),
    CONSTRAINT TURNKEY_MESSAGE_LOG_DETAIL_PK1 PRIMARY KEY (SEQNO, SUBSEQNO, TASK)
)