CREATE TABLE TURNKEY_USER_PROFILE(
    USER_ID VARCHAR2(10) NOT NULL,
    USER_PASSWORD VARCHAR2(100) NOT NULL,
    USER_ROLE VARCHAR2(2),
    CONSTRAINT TURNKEY_USER_PROFILE_PK1 PRIMARY KEY (USER_ID)
)