CREATE TABLE TURNKEY_MESSAGE_LOG (
    SEQNO VARCHAR2(8) NOT NULL,
    SUBSEQNO VARCHAR2(5) NOT NULL,
    UUID VARCHAR2(40) DEFAULT NULL,
    MESSAGE_TYPE VARCHAR2(10) DEFAULT NULL,
    CATEGORY_TYPE VARCHAR2(5) DEFAULT NULL,
    PROCESS_TYPE VARCHAR2(10) DEFAULT NULL,
    FROM_PARTY_ID VARCHAR2(10) DEFAULT NULL,
    TO_PARTY_ID VARCHAR2(10) DEFAULT NULL,
    MESSAGE_DTS VARCHAR2(17) DEFAULT NULL,
    CHARACTER_COUNT VARCHAR2(10) DEFAULT NULL,
    STATUS VARCHAR2(5) DEFAULT NULL,
    IN_OUT_BOUND VARCHAR2(1) DEFAULT NULL,
    FROM_ROUTING_ID VARCHAR2(39) DEFAULT NULL,
    TO_ROUTING_ID VARCHAR2(39) DEFAULT NULL,
    INVOICE_IDENTIFIER VARCHAR2(30) DEFAULT NULL,
    CONSTRAINT TURNKEY_MESSAGE_LOG_PK1 PRIMARY KEY (SEQNO, SUBSEQNO)
)