<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
            attributeFormDefault="unqualified">
    <xsd:simpleType name="MessageTypeEnum">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="A0101"/><!-- A0101.	開立發票 -->
            <xsd:enumeration value="A0102"/><!-- A0102.	發票接收確認 -->
            <xsd:enumeration value="A0201"/><!-- A0201.	作廢發票 -->
            <xsd:enumeration value="A0202"/><!-- A0202.	作廢發票接收確認 -->
            <xsd:enumeration value="A0301"/><!-- A0301.	退回發票 -->
            <xsd:enumeration value="A0302"/><!-- A0302.	退回發票接收確認 -->
            <!-- v31 有這java但應該沒做用 -->
            <xsd:enumeration value="A0401"/><!-- A0401.	開立發票 -->
            <xsd:enumeration value="A0501"/><!-- A0501.	作廢發票 -->
            <xsd:enumeration value="A0601"/><!-- A0601.	退回發票 -->

            <xsd:enumeration value="B0101"/><!-- B0101.	折讓證明單 -->
            <xsd:enumeration value="B0102"/><!-- B0102.	折讓證明單接收確認 -->
            <xsd:enumeration value="B0201"/><!-- B0201.	作廢折讓證明單 -->
            <xsd:enumeration value="B0202"/><!-- B0202.	作廢折讓證明單接收確認 -->

            <!-- v31 有這java但應該沒做用 -->
            <xsd:enumeration value="B0401"/><!-- B0401. 開立折讓證明單 -->
            <xsd:enumeration value="B0501"/><!-- B0501.	折讓證明單通知 -->
            
            <xsd:enumeration value="C0401"/><!-- C0401.	開立發票 -->
            <xsd:enumeration value="C0501"/><!-- C0501.	作廢發票 -->

            <!-- v31 有這java但應該沒做用 -->
            <xsd:enumeration value="C0601"/><!-- C0601.	退回發票 -->

            <xsd:enumeration value="C0701"/><!-- C0701.	註銷發票 -->
            <xsd:enumeration value="D0401"/><!-- D0401.	開立折讓證明單 -->
            <xsd:enumeration value="D0501"/><!-- D0501.	作廢折讓單 -->

            <xsd:enumeration value="F0401"/><!-- F0401.	平台存證開立發票 -->
            <xsd:enumeration value="F0501"/><!-- F0501.	平台存證作廢發票 -->
            <xsd:enumeration value="F0701"/><!-- F0701. 平台存證註銷發票訊息規格 -->
            <xsd:enumeration value="G0401"/><!-- G0401. 平台存證開立折讓證明單 -->
            <xsd:enumeration value="G0501"/><!-- G0501. 平台存證作廢折讓證明單 -->
            
            <xsd:enumeration value="G0701"/><!-- G0701. 註銷折讓單 -->
            <xsd:enumeration value="E0401"/><!-- E0401. 分支機構配號檔 -->
            <xsd:enumeration value="E0402"/><!-- E0402. 空白未使用字軌檔 -->
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="BAN">
        <xsd:restriction base="xsd:string">
            <xsd:maxLength value="10"/>
            <xsd:minLength value="8"/>
        </xsd:restriction>
    </xsd:simpleType>
    <!-- InvoiceType (發票類別) -->
    <xsd:simpleType name="InvoiceTypeEnum">
        <xsd:restriction base="xsd:string">
            <xsd:maxLength value="2"/>
            <xsd:minLength value="2"/>
            <xsd:enumeration value="07"/>
            <xsd:enumeration value="08"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:complexType name="PartyInfoType">
        <xsd:sequence>
            <xsd:element name="PartyId" type="xsd:string"/>
            <xsd:element name="Description" type="xsd:string" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="RoutingInfoType">
        <xsd:sequence>
            <xsd:element name="RoutingId" type="xsd:string"/>
            <xsd:element name="Description" type="xsd:string" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="InfoType">
        <xsd:sequence>
            <xsd:element name="Id" type="xsd:string"/>
            <xsd:element name="Size" type="xsd:positiveInteger"/>
            <xsd:element name="MessageType" type="MessageTypeEnum"/>
            <xsd:element name="Service" type="xsd:string"/>
            <xsd:element name="Action" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="ResultType">
        <xsd:sequence>
            <xsd:element name="Total">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="ResultDetailType" type="ResultDetailType"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="Good">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="ResultDetailType" type="ResultDetailType"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="Failed">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="ResultDetailType" type="ResultDetailType"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="ResultDetailType">
        <xsd:sequence>
            <xsd:element name="Count" type="xsd:int"/>
            <xsd:element name="Invoices" minOccurs="0">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="Invoice" minOccurs="1" maxOccurs="9999">
                            <xsd:complexType>
                                <xsd:sequence>
                                    <xsd:element name="ReferenceNumber">
                                        <xsd:simpleType>
                                            <xsd:restriction base="xsd:string">
                                                <xsd:minLength value="10"/>
                                                <xsd:maxLength value="16"/>
                                            </xsd:restriction>
                                        </xsd:simpleType>
                                    </xsd:element>
                                    <xsd:element name="InvoiceDate">
                                        <xsd:simpleType>
                                            <xsd:restriction base="xsd:string">
                                                <xsd:pattern value="[0-9][0-9][0-9][0-9]((0[1-9]|1[0-2]))((0[1-9]|[1-2][0-9])|(3[0-1]))"/>
                                            </xsd:restriction>
                                        </xsd:simpleType>
                                    </xsd:element>
                                </xsd:sequence>
                            </xsd:complexType>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>
